### ISSUE TITLE
Enable sticky headers after setting Adapter to RecyclerView

### ISSUE THREAD

**Issue by DolphinWing** [DolphinWing/BloodServiceApp#6]
```
FATAL EXCEPTION: main
Process: dolphin.android.apps.BloodServiceApp, PID: 18187
java.lang.IllegalStateException: Adapter is not attached to RecyclerView. Enable sticky headers after setting adapter to RecyclerView.
	at eu.davidea.flexibleadapter.a.b.a(Unknown Source)
	at eu.davidea.flexibleadapter.b$5.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by DolphinWing** [comment]
See https://github.com/davideas/FlexibleAdapter/issues/483

**Comment by DolphinWing** [comment]
still happening in r91
we also have the sticky header in spot location list

**Comment by DolphinWing** [comment]
no issues with r93 in test report
