### ISSUE TITLE
DonateActivity.prepareLocationList IndexOutOfBoundsException

### ISSUE THREAD

**Issue by DolphinWing** [DolphinWing/BloodServiceApp#7]
```
FATAL EXCEPTION: ControllerMessenger
Process: dolphin.android.apps.BloodServiceApp, PID: 18569
java.lang.IndexOutOfBoundsException
	at java.util.Collections$SingletonList.get(Collections.java:283)
	at dolphin.android.apps.BloodServiceApp.provider.DonateActivity.prepareLocationList(Unknown Source)
	at dolphin.android.apps.BloodServiceApp.ui.b.b(Unknown Source)
	at dolphin.android.apps.BloodServiceApp.ui.b.b(Unknown Source)
	at dolphin.android.apps.BloodServiceApp.ui.b$d.onClick(Unknown Source)
	at androidx.appcompat.app.AlertController$a$3.onItemClick(Unknown Source)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3073)
	at android.widget.AbsListView$3.run(AbsListView.java:3910)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:164)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:156)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:136)
	at androidx.test.espresso.action.Tap$1.b(Tap.java:6)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by DolphinWing** [comment]
no proguarded version
```
02-13 16:01:48.880 12894 12894 E AndroidRuntime: Process: dolphin.android.apps.BloodServiceApp, PID: 12894
02-13 16:01:48.880 12894 12894 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at java.util.Collections$SingletonList.get(Collections.java:4861)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at dolphin.android.apps.BloodServiceApp.provider.DonateActivity.prepareLocationList(DonateActivity.kt:240)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at dolphin.android.apps.BloodServiceApp.ui.DonationListFragment.showSearchMapDialog(DonationListFragment.kt:234)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at dolphin.android.apps.BloodServiceApp.ui.DonationListFragment.access$showSearchMapDialog(DonationListFragment.kt:32)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at dolphin.android.apps.BloodServiceApp.ui.DonationListFragment$onItemLongClick$$inlined$let$lambda$1.onClick(DonationListFragment.kt:208)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:350)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1683)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4094)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at android.widget.AbsListView$10.run(AbsListView.java:6583)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
02-13 16:01:48.880 12894 12894 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by DolphinWing** [comment]
錯誤發生在捐血活動名稱有括號的時候

**Comment by DolphinWing** [comment]
no issues with r93 in test report
